### ISSUE TITLE
Monitoring Automatic startup failed

### ISSUE THREAD

**Issue by nieznanysprawiciel** [golemfactory/gamerhash-facade#140]
```
[2024-05-16T18:29:36.376+0200 INFO yapapi.summary] [Job 1] Agreement proposed to provider '0xddaa8f2148a047ac1270255cf9c982d8522694d2' (0xddaa8f2148a047ac1270255cf9c982d8522694d2)
[2024-05-16T18:29:36.733+0200 INFO yapapi.summary] [Job 1] Agreement confirmed by provider '0xddaa8f2148a047ac1270255cf9c982d8522694d2'
[2024-05-16T18:29:37.988+0200 INFO yapapi.summary] Received proposals from 1 provider so far
instances: ['None: pending']
[2024-05-16T18:29:38.356+0200 INFO yapapi.services.service_runner] <AiRuntimeService starting on None [ 0xddaa8f2148a047ac1270255cf9c982d8522694d2 ]> commissioned
['c29b94d58eda46148d0e8e9cf526a5e5']
Request example:

curl -X POST -H 'Authorization: Bearer XUEtFZeP4DNcYZ12mKiYRSGmnvY=' -H 'Content-Type: application/json; charset=utf-8' -H 'Accept: text/event-stream'  -d "{ \"prompt\": \"happy golem\" }" http://127.0.0.1:7465/activity-api/v1/activity/c29b94d58eda46148d0e8e9cf526a5e5/proxy-http/sdapi/v1/txt2img | jq -r ".images[0]" | base64 --decode > output.png && xdg-open output.png
instances: ['None: starting']
instances: ['None: starting']
[2024-05-16T18:29:44.802+0200 WARNING yapapi.services.service_runner] Unhandled exception in service
Traceback (most recent call last):
  File "yapapi/services/service_runner.py", line 397, in _run_instance
  File "App/app.py", line 193, in start
  File "yapapi/services/service_runner.py", line 413, in _run_instance
  File "yapapi/engine.py", line 781, in process_batches
  File "yapapi/engine.py", line 762, in get_batch_results
  File "yapapi/script/__init__.py", line 87, in process_batch_event
yapapi.rest.activity.CommandExecutionError: Command 'Deploy {}' failed on provider; message: 'Activity API error: Monitoring Automatic startup failed'
[2024-05-16T18:29:44.805+0200 INFO yapapi.services.service_runner] <AiRuntimeService terminated on None [ 0xddaa8f2148a047ac1270255cf9c982d8522694d2 ]> decommissioned
[2024-05-16T18:29:44.903+0200 INFO yapapi.summary] [Job 1] Terminated agreement with 0xddaa8f2148a047ac1270255cf9c982d8522694d2
[2024-05-16T18:29:45.006+0200 INFO yapapi.services.service_runner] Restarting service <AiRuntimeService terminated on None [ 0xddaa8f2148a047ac1270255cf9c982d8522694d2 ]>
[2024-05-16T18:29:45.461+0200 INFO yapapi.summary] [Job 1] Accepted invoice from '0xddaa8f2148a047ac1270255cf9c982d8522694d2', amount: 0.001768601550000000
```
Happened on central net configuration of https://github.com/golemfactory/gamerhash-facade/releases/tag/pre-rel-v4.1.0-rc8

Provider side:
```
[2024-05-16T20:21:44.487+0200 DEBUG ya_runtime_ai::process::automatic::monitor] > Traceback (most recent call last):
[2024-05-16T20:21:44.487+0200 DEBUG ya_runtime_ai::process::automatic::monitor] > initial startup: done in 0.001s
[2024-05-16T20:21:44.487+0200 DEBUG ya_runtime_ai::process::automatic::monitor] >   prepare environment:
[2024-05-16T20:21:44.487+0200 DEBUG ya_runtime_ai::process::automatic::monitor] > Launching API server with arguments: --no-download-sd-model --do-not-download-clip --skip-prepare-environment --skip-install --api --api-log --nowebui --api-server-stop --log-startup --skip-torch-cuda-test --skip-python-version-check --skip-version-check --ckpt C:\Users/golem-dev/AppData/Local/GamerHashAI/data/golem/golem-data/provider/exe-unit/cache/v1-5-pruned-emaonly_b2da48d618beddab1887739d75b50a3041c810bc73805a416761185998359b24.safetensors
[2024-05-16T20:21:44.487+0200 DEBUG ya_runtime_ai::process::automatic::monitor] >   File "C:\Users\golem-dev\AppData\Local\GamerHashAI\modules\golem_4.1.0\plugins\ya-automatic-ai\automatic\webui\launch.py", line 48, in <module>
[2024-05-16T20:21:44.487+0200 DEBUG ya_runtime_ai::process::automatic::monitor] > launcher: done in 0.001s
[2024-05-16T20:21:44.487+0200 DEBUG ya_runtime_ai::process::automatic::monitor] > Microsoft Visual C++ Redistributable is not installed, this may lead to the DLL load failure.
[2024-05-16T20:21:44.487+0200 DEBUG ya_runtime_ai::process::automatic::monitor] >                  It can be downloaded at https://aka.ms/vs/16/release/vc_redist.x64.exe
[2024-05-16T20:21:44.487+0200 DEBUG ya_runtime_ai::process::automatic::monitor] >     main()
[2024-05-16T20:21:44.487+0200 DEBUG ya_runtime_ai::process::automatic::monitor] >   File "C:\Users\golem-dev\AppData\Local\GamerHashAI\modules\golem_4.1.0\plugins\ya-automatic-ai\automatic\webui\launch.py", line 44, in main
[2024-05-16T20:21:44.487+0200 DEBUG ya_runtime_ai::process::automatic::monitor] >     start()
[2024-05-16T20:21:44.487+0200 DEBUG ya_runtime_ai::process::automatic::monitor] >   File "C:\Users\golem-dev\AppData\Local\GamerHashAI\modules\golem_4.1.0\plugins\ya-automatic-ai\automatic\webui\modules\launch_utils.py", line 432, in start
[2024-05-16T20:21:44.487+0200 DEBUG ya_runtime_ai::process::automatic::monitor] >     import webui
[2024-05-16T20:21:44.487+0200 DEBUG ya_runtime_ai::process::automatic::monitor] >   File "C:\Users\golem-dev\AppData\Local\GamerHashAI\modules\golem_4.1.0\plugins\ya-automatic-ai\automatic\webui\webui.py", line 13, in <module>
[2024-05-16T20:21:44.488+0200 DEBUG ya_runtime_ai::process::automatic::monitor] >     initialize.imports()
[2024-05-16T20:21:44.488+0200 DEBUG ya_runtime_ai::process::automatic::monitor] >   File "C:\Users\golem-dev\AppData\Local\GamerHashAI\modules\golem_4.1.0\plugins\ya-automatic-ai\automatic\webui\modules\initialize.py", line 14, in imports
[2024-05-16T20:21:44.488+0200 DEBUG ya_runtime_ai::process::automatic::monitor] >     import torch  # noqa: F401
[2024-05-16T20:21:44.488+0200 DEBUG ya_runtime_ai::process::automatic::monitor] >   File "C:\Users\golem-dev\AppData\Local\GamerHashAI\modules\golem_4.1.0\plugins\ya-automatic-ai\automatic\system\python\lib\site-packages\torch\__init__.py", line 133, in <module>
[2024-05-16T20:21:44.488+0200 DEBUG ya_runtime_ai::process::automatic::monitor] >     raise err
[2024-05-16T20:21:44.488+0200 ERROR ya_runtime_ai::process::automatic::monitor] Failed to read line. Err stream did not contain valid UTF-8
[2024-05-16T20:21:44.494+0200 DEBUG ya_runtime_ai::process::automatic::monitor] > Press any key to continue . . . 
[2024-05-16T20:21:44.496+0200 ERROR ya_runtime_ai::process] Failed to start process. Err Monitoring Automatic startup failed
```

**Comment by pwalski** [comment]
Pytorch requires `vcruntime140` dlls on `PATH`
https://github.com/pytorch/pytorch/blob/main/torch/__init__.py#L116

**Comment by pwalski** [comment]
To test `Automatic` startup without VC Redistributables I uninstalled it and then I added `vcruntime140.dll`, `vcruntime140_1.dll`. and `msvcp140.dll` to `PATH` (not `LD_LIBRARY_PATH`). Automatic on startup still printed Warn about missing VC Redistributables but startup had not failed, and request `sdapi/v1/txt2img` worked fine.

**Comment by pwalski** [comment]
Error `Failed to read line. Err stream did not contain valid UTF-8` was caused by this stderr line:
```
OSError: [WinError 126] Nie mo┐na odnalečŠ okreťlonego modu│u. Error loading "C:\Users\golem-dev\Code\gamerha
sh-facade\modules\plugins\ya-automatic-ai\automatic\system\python\lib\site-packages\torch\lib\c10.dll" or one
 of its dependencies.
```
